terraform {
  required_version = ">= 1.12.0"
  required_providers {

  }
}

# AFD Endpoint Resource
resource "azapi_resource" "afd_endpoint" {
  type      = "Microsoft.Cdn/profiles/afdEndpoints@2025-09-01-preview"
  name      = var.name
  parent_id = var.profile_id
  location  = var.location
  tags      = var.tags

  body = {
    properties = {
      autoGeneratedDomainNameLabelScope = var.auto_generated_domain_name_label_scope
      enabledState                      = var.enabled_state
      enforceMtls                       = var.enforce_mtls
    }
  }
}

# AFD Endpoint Routes
module "route" {
  source = "../afd-endpoint-route"

  for_each = var.routes

  name                   = each.value.name
  profile_name           = var.profile_name
  profile_id             = var.profile_id
  afd_endpoint_name      = var.name
  afd_endpoint_id        = azapi_resource.afd_endpoint.id
  origin_group_id        = each.value.origin_group_id
  cache_configuration    = each.value.cache_configuration
  custom_domain_ids      = each.value.custom_domain_ids != null ? each.value.custom_domain_ids : []
  enabled_state          = each.value.enabled_state
  forwarding_protocol    = each.value.forwarding_protocol != null ? each.value.forwarding_protocol : "MatchRequest"
  grpc_state             = each.value.grpc_state
  https_redirect         = each.value.https_redirect != null ? each.value.https_redirect : "Enabled"
  link_to_default_domain = each.value.link_to_default_domain != null ? each.value.link_to_default_domain : "Enabled"
  origin_path            = each.value.origin_path
  patterns_to_match      = each.value.patterns_to_match
  rule_set_ids           = each.value.rule_set_ids != null ? each.value.rule_set_ids : []
  supported_protocols    = each.value.supported_protocols
}
